// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fceffkastvkcwxghjcxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjZWZma2FzdHZrY3d4Z2hqY3hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NjA4ODQsImV4cCI6MjA2NTIzNjg4NH0.F51rMhmoHax91Ik3jy19HPT9moh5DwQz0RwDR-VP27Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);